export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME'
export const GET_COUNTRY_DETAIL= 'GET_COUNTRY_DETAIL';
export const FILTER_BY_POP = 'FILTER_BY_POP';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const GET_ACTIVITIES = 'GET_ACTIVITIES'